import sys
import rrdtool
from Notify import send_alert_attached
import time

rrdpath = '/home/angelgm/Angel/Servicios en Red/ADSR/6-AdministraciónDeRendimiento/RRD/'
imgpath = '/home/angelgm/Angel/Servicios en Red/ADSR/6-AdministraciónDeRendimiento/IMG/'

def generarGrafica(ultima_lectura, primera_lectura):
    # tiempo_final = int(ultima_lectura)
    # tiempo_inicial = primera_lectura
    ret = rrdtool.graphv(imgpath + "cpuload.png",
                         "--start", str(primera_lectura),
                         "--end", str(ultima_lectura),
                         "--vertical-label=CPU load",
                         "--lower-limit", "0",
                         "--upper-limit", "100",
                         "--title=Carga de cada procesador y el promedio de todos",
                         "DEF:cargaCPU=" + rrdpath + "monitoreo.rrd:CPUload:AVERAGE",
                         "VDEF:cargaMAX=cargaCPU,MAXIMUM",
                         "VDEF:cargaMIN=cargaCPU,MINIMUM",
                         "VDEF:cargaSTDEV=cargaCPU,STDEV",
                         "VDEF:cargaLAST=cargaCPU,LAST",
                         # "CDEF:umbral15=cargaCPU,15,LT,0,cargaCPU,IF",
                         "AREA:cargaCPU#00FF00:Carga promedio del CPU",
                         # "AREA:umbral15#FF9F00:Carga CPU mayor de 15",
                         # "HRULE:15#FF0000:Umbral  15%",
                         "PRINT:cargaLAST:%6.2lf",
                         "GPRINT:cargaMIN:%6.2lf %SMIN",
                         "GPRINT:cargaSTDEV:%6.2lf %SSTDEV",
                         "GPRINT:cargaLAST:%6.2lf %SLAST",
                         "DEF:cargaCPU1=" + rrdpath + "monitoreo.rrd:CPUload1:AVERAGE",
                         "VDEF:cargaMAX1=cargaCPU1,MAXIMUM",
                         "VDEF:cargaMIN1=cargaCPU1,MINIMUM",
                         "VDEF:cargaSTDEV1=cargaCPU1,STDEV",
                         "VDEF:cargaLAST1=cargaCPU1,LAST",
                         "AREA:cargaCPU1#00FF00:Carga del CPU 1",
                         "PRINT:cargaLAST1:%6.2lf",
                         "GPRINT:cargaMIN1:%6.2lf %SMIN",
                         "GPRINT:cargaSTDEV1:%6.2lf %SSTDEV",
                         "GPRINT:cargaLAST1:%6.2lf %SLAST",
                         "DEF:cargaCPU2=" + rrdpath + "monitoreo.rrd:CPUload2:AVERAGE",
                         "VDEF:cargaMAX2=cargaCPU2,MAXIMUM",
                         "VDEF:cargaMIN2=cargaCPU2,MINIMUM",
                         "VDEF:cargaSTDEV2=cargaCPU2,STDEV",
                         "VDEF:cargaLAST2=cargaCPU2,LAST",
                         "AREA:cargaCPU2#00FF00:Carga del CPU 2",
                         "PRINT:cargaLAST2:%6.2lf",
                         "GPRINT:cargaMIN2:%6.2lf %SMIN",
                         "GPRINT:cargaSTDEV2:%6.2lf %SSTDEV",
                         "GPRINT:cargaLAST2:%6.2lf %SLAST",
                         "DEF:cargaCPU3=" + rrdpath + "monitoreo.rrd:CPUload3:AVERAGE",
                         "VDEF:cargaMAX3=cargaCPU3,MAXIMUM",
                         "VDEF:cargaMIN3=cargaCPU3,MINIMUM",
                         "VDEF:cargaSTDEV3=cargaCPU3,STDEV",
                         "VDEF:cargaLAST3=cargaCPU3,LAST",
                         "AREA:cargaCPU3#00FF00:Carga del CPU 3",
                         "PRINT:cargaLAST3:%6.2lf",
                         "GPRINT:cargaMIN3:%6.2lf %SMIN",
                         "GPRINT:cargaSTDEV3:%6.2lf %SSTDEV",
                         "GPRINT:cargaLAST3:%6.2lf %SLAST",
                         "DEF:cargaCPU4=" + rrdpath + "monitoreo.rrd:CPUload4:AVERAGE",
                         "VDEF:cargaMAX4=cargaCPU4,MAXIMUM",
                         "VDEF:cargaMIN4=cargaCPU4,MINIMUM",
                         "VDEF:cargaSTDEV4=cargaCPU4,STDEV",
                         "VDEF:cargaLAST4=cargaCPU4,LAST",
                         "AREA:cargaCPU4#00FF00:Carga del CPU 4",
                         "PRINT:cargaLAST4:%6.2lf",
                         "GPRINT:cargaMIN4:%6.2lf %SMIN",
                         "GPRINT:cargaSTDEV4:%6.2lf %SSTDEV",
                         "GPRINT:cargaLAST4:%6.2lf %SLAST",
                         "DEF:cargaCPU5=" + rrdpath + "monitoreo.rrd:CPUload5:AVERAGE",
                         "VDEF:cargaMAX5=cargaCPU5,MAXIMUM",
                         "VDEF:cargaMIN5=cargaCPU5,MINIMUM",
                         "VDEF:cargaSTDEV5=cargaCPU5,STDEV",
                         "VDEF:cargaLAST5=cargaCPU5,LAST",
                         "AREA:cargaCPU5#00FF00:Carga del CPU 5",
                         "PRINT:cargaLAST5:%6.2lf",
                         "GPRINT:cargaMIN5:%6.2lf %SMIN",
                         "GPRINT:cargaSTDEV5:%6.2lf %SSTDEV",
                         "GPRINT:cargaLAST5:%6.2lf %SLAST",
                         "DEF:cargaCPU6=" + rrdpath + "monitoreo.rrd:CPUload6:AVERAGE",
                         "VDEF:cargaMAX6=cargaCPU6,MAXIMUM",
                         "VDEF:cargaMIN6=cargaCPU6,MINIMUM",
                         "VDEF:cargaSTDEV6=cargaCPU6,STDEV",
                         "VDEF:cargaLAST6=cargaCPU6,LAST",
                         "AREA:cargaCPU6#00FF00:Carga del CPU 6",
                         "PRINT:cargaLAST6:%6.2lf",
                         "GPRINT:cargaMIN6:%6.2lf %SMIN",
                         "GPRINT:cargaSTDEV6:%6.2lf %SSTDEV",
                         "GPRINT:cargaLAST6:%6.2lf %SLAST",
                         "DEF:cargaCPU7=" + rrdpath + "monitoreo.rrd:CPUload7:AVERAGE",
                         "VDEF:cargaMAX7=cargaCPU7,MAXIMUM",
                         "VDEF:cargaMIN7=cargaCPU7,MINIMUM",
                         "VDEF:cargaSTDEV7=cargaCPU7,STDEV",
                         "VDEF:cargaLAST7=cargaCPU7,LAST",
                         "AREA:cargaCPU7#00FF00:Carga del CPU 7",
                         "PRINT:cargaLAST7:%6.2lf",
                         "GPRINT:cargaMIN7:%6.2lf %SMIN",
                         "GPRINT:cargaSTDEV7:%6.2lf %SSTDEV",
                         "GPRINT:cargaLAST7:%6.2lf %SLAST",
                         "DEF:cargaCPU8=" + rrdpath + "monitoreo.rrd:CPUload8:AVERAGE",
                         "VDEF:cargaMAX8=cargaCPU8,MAXIMUM",
                         "VDEF:cargaMIN8=cargaCPU8,MINIMUM",
                         "VDEF:cargaSTDEV8=cargaCPU8,STDEV",
                         "VDEF:cargaLAST8=cargaCPU8,LAST",
                         "AREA:cargaCPU8#00FF00:Carga del CPU 8",
                         "PRINT:cargaLAST8:%6.2lf",
                         "GPRINT:cargaMIN8:%6.2lf %SMIN",
                         "GPRINT:cargaSTDEV8:%6.2lf %SSTDEV",
                         "GPRINT:cargaLAST8:%6.2lf %SLAST",
                         "DEF:cargaCPU9=" + rrdpath + "monitoreo.rrd:CPUload9:AVERAGE",
                         "VDEF:cargaMAX9=cargaCPU9,MAXIMUM",
                         "VDEF:cargaMIN9=cargaCPU9,MINIMUM",
                         "VDEF:cargaSTDEV9=cargaCPU9,STDEV",
                         "VDEF:cargaLAST9=cargaCPU9,LAST",
                         "AREA:cargaCPU9#00FF00:Carga del CPU 9",
                         "PRINT:cargaLAST9:%6.2lf",
                         "GPRINT:cargaMIN9:%6.2lf %SMIN",
                         "GPRINT:cargaSTDEV9:%6.2lf %SSTDEV",
                         "GPRINT:cargaLAST9:%6.2lf %SLAST",
                         "DEF:cargaCPU10=" + rrdpath + "monitoreo.rrd:CPUload10:AVERAGE",
                         "VDEF:cargaMAX10=cargaCPU10,MAXIMUM",
                         "VDEF:cargaMIN10=cargaCPU10,MINIMUM",
                         "VDEF:cargaSTDEV10=cargaCPU10,STDEV",
                         "VDEF:cargaLAST10=cargaCPU10,LAST",
                         "AREA:cargaCPU10#00FF00:Carga del CPU 10",
                         "PRINT:cargaLAST10:%6.2lf",
                         "GPRINT:cargaMIN10:%6.2lf %SMIN",
                         "GPRINT:cargaSTDEV10:%6.2lf %SSTDEV",
                         "GPRINT:cargaLAST10:%6.2lf %SLAST",
                         "DEF:cargaCPU11=" + rrdpath + "monitoreo.rrd:CPUload11:AVERAGE",
                         "VDEF:cargaMAX11=cargaCPU11,MAXIMUM",
                         "VDEF:cargaMIN11=cargaCPU11,MINIMUM",
                         "VDEF:cargaSTDEV11=cargaCPU11,STDEV",
                         "VDEF:cargaLAST11=cargaCPU11,LAST",
                         "AREA:cargaCPU11#00FF00:Carga del CPU 11",
                         "PRINT:cargaLAST11:%6.2lf",
                         "GPRINT:cargaMIN11:%6.2lf %SMIN",
                         "GPRINT:cargaSTDEV11:%6.2lf %SSTDEV",
                         "GPRINT:cargaLAST11:%6.2lf %SLAST",
                         "DEF:cargaCPU12=" + rrdpath + "monitoreo.rrd:CPUload12:AVERAGE",
                         "VDEF:cargaMAX12=cargaCPU12,MAXIMUM",
                         "VDEF:cargaMIN12=cargaCPU12,MINIMUM",
                         "VDEF:cargaSTDEV12=cargaCPU12,STDEV",
                         "VDEF:cargaLAST12=cargaCPU12,LAST",
                         "AREA:cargaCPU12#00FF00:Carga del CPU 12",
                         "PRINT:cargaLAST12:%6.2lf",
                         "GPRINT:cargaMIN12:%6.2lf %SMIN",
                         "GPRINT:cargaSTDEV12:%6.2lf %SSTDEV",
                         "GPRINT:cargaLAST12:%6.2lf %SLAST",
                         "DEF:cargaCPU13=" + rrdpath + "monitoreo.rrd:CPUload13:AVERAGE",
                         "VDEF:cargaMAX13=cargaCPU13,MAXIMUM",
                         "VDEF:cargaMIN13=cargaCPU13,MINIMUM",
                         "VDEF:cargaSTDEV13=cargaCPU13,STDEV",
                         "VDEF:cargaLAST13=cargaCPU13,LAST",
                         "AREA:cargaCPU13#00FF00:Carga del CPU 13",
                         "PRINT:cargaLAST13:%6.2lf",
                         "GPRINT:cargaMIN13:%6.2lf %SMIN",
                         "GPRINT:cargaSTDEV13:%6.2lf %SSTDEV",
                         "GPRINT:cargaLAST13:%6.2lf %SLAST",
                         "DEF:cargaCPU14=" + rrdpath + "monitoreo.rrd:CPUload14:AVERAGE",
                         "VDEF:cargaMAX14=cargaCPU14,MAXIMUM",
                         "VDEF:cargaMIN14=cargaCPU14,MINIMUM",
                         "VDEF:cargaSTDEV14=cargaCPU14,STDEV",
                         "VDEF:cargaLAST14=cargaCPU14,LAST",
                         "AREA:cargaCPU14#00FF00:Carga del CPU 14",
                         "PRINT:cargaLAST14:%6.2lf",
                         "GPRINT:cargaMIN14:%6.2lf %SMIN",
                         "GPRINT:cargaSTDEV14:%6.2lf %SSTDEV",
                         "GPRINT:cargaLAST14:%6.2lf %SLAST",
                         "DEF:cargaCPU15=" + rrdpath + "monitoreo.rrd:CPUload15:AVERAGE",
                         "VDEF:cargaMAX15=cargaCPU15,MAXIMUM",
                         "VDEF:cargaMIN15=cargaCPU15,MINIMUM",
                         "VDEF:cargaSTDEV15=cargaCPU15,STDEV",
                         "VDEF:cargaLAST15=cargaCPU15,LAST",
                         "AREA:cargaCPU15#00FF00:Carga del CPU 15",
                         "PRINT:cargaLAST15:%6.2lf",
                         "GPRINT:cargaMIN15:%6.2lf %SMIN",
                         "GPRINT:cargaSTDEV15:%6.2lf %SSTDEV",
                         "GPRINT:cargaLAST15:%6.2lf %SLAST",
                         "DEF:cargaCPU16=" + rrdpath + "monitoreo.rrd:CPUload16:AVERAGE",
                         "VDEF:cargaMAX16=cargaCPU16,MAXIMUM",
                         "VDEF:cargaMIN16=cargaCPU16,MINIMUM",
                         "VDEF:cargaSTDEV16=cargaCPU16,STDEV",
                         "VDEF:cargaLAST16=cargaCPU16,LAST",
                         "AREA:cargaCPU16#00FF00:Carga del CPU 16",
                         "PRINT:cargaLAST16:%6.2lf",
                         "GPRINT:cargaMIN16:%6.2lf %SMIN",
                         "GPRINT:cargaSTDEV16:%6.2lf %SSTDEV",
                         "GPRINT:cargaLAST16:%6.2lf %SLAST")
    print(ret)

    ret = rrdtool.graphv(imgpath + "ramusage.png",
                         "--start", str(primera_lectura),
                         "--end", str(ultima_lectura),
                         "--vertical-label=RAM usage",
                         "--lower-limit", "0",
                         "--upper-limit", "100",
                         "--title=Uso de la memoria RAM en %",
                         "DEF:usageRAM=" + rrdpath + "monitoreo.rrd:RAMusage:AVERAGE",
                         "VDEF:RAMMAX=usageRAM,MAXIMUM",
                         "VDEF:RAMMIN=usageRAM,MINIMUM",
                         "VDEF:RAMSTDEV=usageRAM,STDEV",
                         "VDEF:RAMLAST=usageRAM,LAST",
                         # "CDEF:umbral15=usageRAM,15,LT,0,usageRAM,IF",
                         "AREA:usageRAM#00FF00:Uso de RAM",
                         # "AREA:umbral15#FF9F00:Carga CPU mayor de 15",
                         # "HRULE:15#FF0000:Umbral  15%",
                         "PRINT:RAMLAST:%6.2lf",
                         "GPRINT:RAMMIN:%6.2lf %SMIN",
                         "GPRINT:RAMSTDEV:%6.2lf %SSTDEV",
                         "GPRINT:RAMLAST:%6.2lf %SLAST")
    print(ret)


while 1:
    ultima_actualizacion = rrdtool.lastupdate(rrdpath + "monitoreo.rrd")
    primera_actualizacion = rrdtool.first(rrdpath + "monitoreo.rrd")
    timestampf = ultima_actualizacion['date'].timestamp()
    dato_CPU = ultima_actualizacion['ds']["CPUload"]
    dato_RAM = ultima_actualizacion['ds']["RAMusage"]
    generarGrafica(int(timestampf), int(primera_actualizacion))
    """if dato_CPU > 15:
        generarGrafica(int(timestampf), int(timestampi))
        send_alert_attached("CPU sobrepasa el umbral")
        print("CPU sobrepasa el umbral")

    if dato_RAM > 15:
        generarGrafica(int(timestampf), int(timestampi))
        send_alert_attached("RAM sobrepasa el umbral")
        print("RAM sobrepasa el umbral")"""

    time.sleep(20)
